stack:
  name: "crm-admin"
  account: 183631317390
  region: us-west-1

githubRepoOwner: "miguel-merlin"
githubRepoName: CRM-Admin
githubAccessTokenName: prod/gh-access-token

dev:
  deploy: false
  environmentType: dev
  branchName: dev
  pipelineConfig:
    name: crm-admin-dev-pipeline
  s3Config:
    bucketName: crm-admin-dev-artifacts
    artifactsBucket: crm-admin-dev-artifacts-bucket
    publicAccess: false
    indexFile: index.html
    errorFile: index.html

prod:
  deploy: true
  environmentType: prod
  branchName: main
  pipelineConfig:
    name: crm-admin-prod-pipeline
  s3Config:
    bucketName: crm-admin-prod-artifacts
    artifactsBucket: crm-admin-prod-artifacts-bucket
    publicAccess: true
    indexFile: index.html
    errorFile: index.html
